-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."RideLog"
(
    "Id" integer NOT NULL,
    "RideId" integer NOT NULL,
    "PassengersNumber" integer,
    "Accident" text,
    PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Ride"
(
    "Id" integer NOT NULL,
    "BusId" integer NOT NULL,
    "DriverId" integer NOT NULL,
    "TrackId" integer NOT NULL,
    "Date" date NOT NULL,
    PRIMARY KEY ("Id")
);

COMMENT ON TABLE public."Ride"
    IS 'jeden przejazd w konkretnym czasie, z konkretnym kierowca';

CREATE TABLE IF NOT EXISTS public."Driver"
(
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Lastname" text NOT NULL,
    "License" text,
    "Selary" money,
    "HolidaysDays" integer,
    PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."DriverUnavailability"
(
    "DriverId" integer NOT NULL,
    "StartDate" date NOT NULL,
    "EndDate" date NOT NULL,
    "Reason" text,
    PRIMARY KEY ("DriverId")
);

CREATE TABLE IF NOT EXISTS public."Track"
(
    "Id" integer NOT NULL,
    "LineId" integer NOT NULL,
    "StartTime" time without time zone NOT NULL,
    "BusTypeId" integer NOT NULL,
    PRIMARY KEY ("Id")
);

COMMENT ON TABLE public."Track"
    IS 'Kurs - definiuje czas odjazdu, jaka linia oraz typ busa potrzebny';

CREATE TABLE IF NOT EXISTS public."Line"
(
    "Id" integer NOT NULL,
    "LineName" text NOT NULL,
    PRIMARY KEY ("Id")
);

COMMENT ON TABLE public."Line"
    IS 'linia ';

CREATE TABLE IF NOT EXISTS public."Route"
(
    "Id" integer NOT NULL,
    "LineId" integer NOT NULL,
    "BusStopId" integer NOT NULL,
    "Order" integer NOT NULL,
    PRIMARY KEY ("Id")
);

COMMENT ON TABLE public."Route"
    IS 'przystanki po kolei';

CREATE TABLE IF NOT EXISTS public."BusStop"
(
    "Id" integer NOT NULL,
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    "Name" text NOT NULL,
    "Adress" text NOT NULL,
    PRIMARY KEY ("Id")
);

COMMENT ON TABLE public."BusStop"
    IS 'przystanek';

CREATE TABLE IF NOT EXISTS public."Trackroute"
(
    "Id" integer NOT NULL,
    "TrackId" integer NOT NULL,
    "RouteId" integer NOT NULL,
    "Time" time without time zone NOT NULL,
    PRIMARY KEY ("Id")
);

COMMENT ON TABLE public."Trackroute"
    IS 'planowany czas przyjazdu na przystanek';

CREATE TABLE IF NOT EXISTS public."RealTimeTrackroute"
(
    "RideId" integer NOT NULL,
    "TrackRouteId" integer NOT NULL,
    "realTime" time without time zone NOT NULL
);

COMMENT ON TABLE public."RealTimeTrackroute"
    IS 'realny czas dojazdu na przystanek pojazdu';

CREATE TABLE IF NOT EXISTS public."BusType"
(
    "Id" integer NOT NULL,
    "Description" text NOT NULL,
    "Shortcut" text NOT NULL,
    PRIMARY KEY ("Id")
);

COMMENT ON TABLE public."BusType"
    IS 'rodzaj busa';

CREATE TABLE IF NOT EXISTS public."Bus"
(
    "Id" integer NOT NULL,
    "Capacity" integer,
    "BusTypeId" integer,
    "NextCarReviev" date,
    "ActualEventLogId" integer,
    PRIMARY KEY ("Id")
);

COMMENT ON TABLE public."Bus"
    IS 'pojazd mechaniczny';

CREATE TABLE IF NOT EXISTS public."Refueling"
(
    "BusId" integer NOT NULL,
    "Quantity" double precision NOT NULL,
    "Date" date NOT NULL
);

COMMENT ON TABLE public."Refueling"
    IS 'tankowanie';

CREATE TABLE IF NOT EXISTS public."EventLog"
(
    "Id" integer NOT NULL,
    "BusId" integer NOT NULL,
    "EventId" integer,
    status text,
    "StartDate" date NOT NULL,
    "EndDate" date,
    PRIMARY KEY ("Id")
);

COMMENT ON TABLE public."EventLog"
    IS 'tablica przechowuja wszystkie aktualne oraz przeszle zdarzenia, awarie itd';

CREATE TABLE IF NOT EXISTS public."Event"
(
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    PRIMARY KEY ("Id")
);

COMMENT ON TABLE public."Event"
    IS 'zbior mozliwych zdarzen';

ALTER TABLE IF EXISTS public."RideLog"
    ADD FOREIGN KEY ("RideId")
    REFERENCES public."Ride" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Ride"
    ADD FOREIGN KEY ("DriverId")
    REFERENCES public."Driver" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Ride"
    ADD FOREIGN KEY ("BusId")
    REFERENCES public."Bus" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Ride"
    ADD FOREIGN KEY ("TrackId")
    REFERENCES public."Track" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."DriverUnavailability"
    ADD FOREIGN KEY ("DriverId")
    REFERENCES public."Driver" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Track"
    ADD FOREIGN KEY ("BusTypeId")
    REFERENCES public."BusType" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Track"
    ADD FOREIGN KEY ("LineId")
    REFERENCES public."Line" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Route"
    ADD FOREIGN KEY ("LineId")
    REFERENCES public."Line" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Route"
    ADD FOREIGN KEY ("BusStopId")
    REFERENCES public."BusStop" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Trackroute"
    ADD FOREIGN KEY ("TrackId")
    REFERENCES public."Track" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Trackroute"
    ADD FOREIGN KEY ("RouteId")
    REFERENCES public."Route" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."RealTimeTrackroute"
    ADD FOREIGN KEY ("RideId")
    REFERENCES public."Ride" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."RealTimeTrackroute"
    ADD FOREIGN KEY ("TrackRouteId")
    REFERENCES public."Trackroute" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Bus"
    ADD FOREIGN KEY ("BusTypeId")
    REFERENCES public."BusType" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Refueling"
    ADD FOREIGN KEY ("BusId")
    REFERENCES public."Bus" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."EventLog"
    ADD FOREIGN KEY ("EventId")
    REFERENCES public."Event" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."EventLog"
    ADD FOREIGN KEY ("BusId")
    REFERENCES public."Bus" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;