BEGIN;

--line a,b,c,1,2,3
insert into line(line_name) values 
('A'),
('B'),
('C'),
('1'),
('2'),
('3');

--przystanki w 2 strony oznaczone 1 jadace na petle i 2 na dworzec
insert into bus_stop(name, adress) values
('dworzec1', 'dworcowa 44'),
('zielony1', 'zielona 4'),
('poziomka1', 'poziomkowa 65'),
('malina1', 'malinowa 16'),
('truskawka1', 'truskawkowa 1'),
('petla1', 'paprocanska 34'),
('zolty1', 'zolta 16'),
('szary1', 'szara 54'),
('niebieski1', 'niebieska 98'),
('kosciol1', 'koscielna 5'),
('ratusz1', 'urzedowa 13'),
('basen1', 'mokra 2'),
('czarny1', 'czarna 4'),
('hipermarkety1', 'zakupowa 12'),
('silownia1', 'ciezka 18'),
('dworzec2', 'dworcowa 44'),
('zielony2', 'zielona 4'),
('poziomka2', 'poziomkowa 65'),
('malina2', 'malinowa 16'),
('truskawka2', 'truskawkowa 1'),
('petla2', 'paprocanska 34'),
('zolty2', 'zolta 16'),
('szary2', 'szara 54'),
('niebieski2', 'niebieska 98'),
('kosciol2', 'koscielna 5'),
('ratusz2', 'urzedowa 13'),
('basen2', 'mokra 2'),
('czarny2', 'czarna 4'),
('hipermarkety2', 'zakupowa 12'),
('silownia2', 'ciezka 18')
;

--dodanie 4 typow busow niskopodlogowy / wysokopodlogowy x pojedynczy / podwojny
insert into bus_type (description, shortcut, capacity) values
('pojedynczy, niskopodłogowy', 'sl','25'),
('pojedynczy, wysokopodłogowy', 'sh','25'),
('podwojny, niskopodłogowy', 'dl','75'),
('podwojny, wysokopodłogowy', 'dh','75');

--5 kierowcow
insert into driver (name, lastname, license, salary, holidays_days) values
('Jan', 'Kowalski', 'D2',500,2),
('Nikodem','Wspanialy','D1',5000,12),
('Alan','Pawleta','D2',3000,24),
('Kamil','Nabozny','D1',11000,24),
('Bartosz','Pokorski','D2',4000,20),
('Lukasz','Wojczuk','D1',13000,24)
;

--dodanie listy zdarzen podstawowej
insert into event (name, description) values
('przeglad', 'pojazd jest na przegladzie'),
('awaria silika', 'awaria silnika, pojazd nie zdatny do jazdy'),
('dziurawa opona', 'pojazd uszkodzony')
;

--trasa dla linii
insert into route  values
(default,(select id from line where line_name = '1'), (select id from bus_stop where name = 'dworzec1'),'0'),
(default,(select id from line where line_name = '1'), (select id from bus_stop where name = 'zielony1'),1),
(default,(select id from line where line_name = '1'), (select id from bus_stop where name = 'poziomka1'),'2'),
(default,(select id from line where line_name = '1'), (select id from bus_stop where name = 'malina1'),'3'),
(default,(select id from line where line_name = '1'), (select id from bus_stop where name = 'truskawka1'),'4'),
(default,(select id from line where line_name = '1'), (select id from bus_stop where name = 'petla1'),'5'),

(default,(select id from line where line_name = '2'), (select id from bus_stop where name = 'petla2'),'0'),
(default,(select id from line where line_name = '2'), (select id from bus_stop where name = 'truskawka2'),'1'),
(default,(select id from line where line_name = '2'), (select id from bus_stop where name = 'malina2'),'2'),
(default,(select id from line where line_name = '2'), (select id from bus_stop where name = 'poziomka2'),'3'),
(default,(select id from line where line_name = '2'), (select id from bus_stop where name = 'zielony2'),'4'),
(default,(select id from line where line_name = '2'), (select id from bus_stop where name = 'dworzec2'),'5'),

(default,(select id from line where line_name = '3'), (select id from bus_stop where name = 'dworzec1'),'0'),
(default,(select id from line where line_name = '3'), (select id from bus_stop where name = 'zielony1'),'1'),
(default,(select id from line where line_name = '3'), (select id from bus_stop where name = 'niebieski1'),'2'),
(default,(select id from line where line_name = '3'), (select id from bus_stop where name = 'szary1'),'3'),
(default,(select id from line where line_name = '3'), (select id from bus_stop where name = 'zolty1'),'4'),
(default,(select id from line where line_name = '3'), (select id from bus_stop where name = 'czarny1'),'5'),
(default,(select id from line where line_name = '3'), (select id from bus_stop where name = 'petla1'),'6'),

(default,(select id from line where line_name = 'A'), (select id from bus_stop where name = 'dworzec1'),'0'),
(default,(select id from line where line_name = 'A'), (select id from bus_stop where name = 'kosciol1'),'1'),
(default,(select id from line where line_name = 'A'), (select id from bus_stop where name = 'niebieski1'),'2'),
(default,(select id from line where line_name = 'A'), (select id from bus_stop where name = 'szary1'),'3'),
(default,(select id from line where line_name = 'A'), (select id from bus_stop where name = 'truskawka1'),'4'),
(default,(select id from line where line_name = 'A'), (select id from bus_stop where name = 'petla1'),'5'),
 
(default,(select id from line where line_name = 'B'), (select id from bus_stop where name = 'petla2'),'0'),
(default,(select id from line where line_name = 'B'), (select id from bus_stop where name = 'czarny2'),'1'),
(default,(select id from line where line_name = 'B'), (select id from bus_stop where name = 'basen2'),'2'),
(default,(select id from line where line_name = 'B'), (select id from bus_stop where name = 'ratusz2'),'3'),
(default,(select id from line where line_name = 'B'), (select id from bus_stop where name = 'kosciol2'),'4'),
(default,(select id from line where line_name = 'B'), (select id from bus_stop where name = 'dworzec2'),'5'),

(default,(select id from line where line_name = 'C'), (select id from bus_stop where name = 'dworzec1'),'0'),
(default,(select id from line where line_name = 'C'), (select id from bus_stop where name = 'kosciol1'),'1'),
(default,(select id from line where line_name = 'C'), (select id from bus_stop where name = 'silownia1'),'2'),
(default,(select id from line where line_name = 'C'), (select id from bus_stop where name = 'hipermarkety1'),'3'),
(default,(select id from line where line_name = 'C'), (select id from bus_stop where name = 'basen1'),'4'),
(default,(select id from line where line_name = 'C'), (select id from bus_stop where name = 'czarny1'),'5'),
(default,(select id from line where line_name = 'C'), (select id from bus_stop where name = 'petla1'),'6')
;

--busy
insert into bus (bus_type_id, next_car_review) values
((select id from bus_type where shortcut = 'sl'), '2024-10-16'),
((select id from bus_type where shortcut = 'sl'), '2024-10-18'),
((select id from bus_type where shortcut = 'dl'), '2025-01-12'),
((select id from bus_type where shortcut = 'sh'), '2024-08-12'),
((select id from bus_type where shortcut = 'dh'), '2024-12-13'),
((select id from bus_type where shortcut = 'sl'), '2024-11-01')
;

--niedostepnosc driverow
insert into driver_unavailability (driver_id, start_date, end_date, reason) values
((select id from driver where name = 'Nikodem' and lastname = 'Wspanialy'), '2024-05-12', '2024-05-19', 'urlop')
;

--track - ktora linia kiedy jedzie
insert into track (id, line_id, start_time, bus_type_id) values
(Default,(select id from line where line_name = '1'), '10:00:00', (select id from bus_type where shortcut = 'sl')),
(Default,(select id from line where line_name = '1'), '11:00:00', (select id from bus_type where shortcut = 'sl')),
(Default,(select id from line where line_name = '1'), '12:00:00', (select id from bus_type where shortcut = 'sl')),
(Default,(select id from line where line_name = '1'), '13:00:00', (select id from bus_type where shortcut = 'sl')),
(Default,(select id from line where line_name = '1'), '14:00:00', (select id from bus_type where shortcut = 'sl')),
(Default,(select id from line where line_name = '1'), '15:00:00', (select id from bus_type where shortcut = 'sl')),
(Default,(select id from line where line_name = '1'), '16:00:00', (select id from bus_type where shortcut = 'sl')),
(Default,(select id from line where line_name = '1'), '17:00:00', (select id from bus_type where shortcut = 'sl')),
(Default,(select id from line where line_name = '1'), '18:00:00', (select id from bus_type where shortcut = 'sl')),
(Default,(select id from line where line_name = '1'), '19:00:00', (select id from bus_type where shortcut = 'sl')),
(Default,(select id from line where line_name = '1'), '20:00:00', (select id from bus_type where shortcut = 'sl')),

(Default,(select id from line where line_name = '2'), '12:30:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = '2'), '15:20:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = '2'), '18:10:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = '2'), '22:00:00', (select id from bus_type where shortcut = 'dl')),

(Default,(select id from line where line_name = '3'), '19:00:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = '3'), '20:00:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = '3'), '21:00:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = '3'), '22:00:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = '3'), '23:00:00', (select id from bus_type where shortcut = 'dl')),

(Default,(select id from line where line_name = 'C'), '06:15:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = 'C'), '06:45:00', (select id from bus_type where shortcut = 'sl')),
(Default,(select id from line where line_name = 'C'), '07:15:00', (select id from bus_type where shortcut = 'sl')),
(Default,(select id from line where line_name = 'C'), '07:45:00', (select id from bus_type where shortcut = 'sl')),
(Default,(select id from line where line_name = 'C'), '08:15:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = 'C'), '08:45:00', (select id from bus_type where shortcut = 'dl')),

(Default,(select id from line where line_name = 'A'), '09:00:00', (select id from bus_type where shortcut = 'dh')),
(Default,(select id from line where line_name = 'A'), '09:30:00', (select id from bus_type where shortcut = 'dh')),
(Default,(select id from line where line_name = 'A'), '12:00:00', (select id from bus_type where shortcut = 'dh')),
(Default,(select id from line where line_name = 'A'), '12:30:00', (select id from bus_type where shortcut = 'dh')),
(Default,(select id from line where line_name = 'A'), '15:00:00', (select id from bus_type where shortcut = 'dh')),
(Default,(select id from line where line_name = 'A'), '15:30:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = 'A'), '20:00:00', (select id from bus_type where shortcut = 'dl')),

(Default,(select id from line where line_name = 'B'), '07:00:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = 'B'), '08:00:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = 'B'), '09:00:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = 'B'), '10:00:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = 'B'), '11:00:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = 'B'), '12:00:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = 'B'), '13:00:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = 'B'), '14:00:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = 'B'), '15:00:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = 'B'), '16:00:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = 'B'), '17:00:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = 'B'), '18:00:00', (select id from bus_type where shortcut = 'dl')),
(Default,(select id from line where line_name = 'B'), '19:00:00', (select id from bus_type where shortcut = 'dl'))
;

--tankowanie
insert into refueling (bus_id, quantity, date) values
(1, 100.0, '2024-05-10'),
(1, 65.0, '2024-05-11')
;

--dziennik zdarzen 
insert into event_log (bus_id, event_id, status, start_date, end_date) values
(1, 1, 'status', '2024-06-12','2024-06-13'),
(2, 2, 'awaria na trasie', '2024-05-10',DEFAULT)
;

--trackroute XD
insert into trackroute (track_id, route_id,time) values
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '10:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 0), '10:00:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '10:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 1), '10:06:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '10:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 2), '10:16:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '10:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 3), '10:29:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '10:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 4), '10:38:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '10:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 5), '10:46:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '11:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 0), '11:00:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '11:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 1), '11:12:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '11:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 2), '11:25:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '11:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 3), '11:37:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '11:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 4), '11:50:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '11:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 5), '12:04:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '12:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 0), '12:00:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '12:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 1), '12:12:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '12:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 2), '12:20:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '12:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 3), '12:34:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '12:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 4), '12:43:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '12:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 5), '12:52:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '13:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 0), '13:00:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '13:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 1), '13:11:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '13:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 2), '13:17:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '13:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 3), '13:30:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '13:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 4), '13:41:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '13:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 5), '13:53:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '14:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 0), '14:00:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '14:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 1), '14:06:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '14:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 2), '14:17:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '14:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 3), '14:28:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '14:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 4), '14:34:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '14:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 5), '14:46:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '15:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 0), '15:00:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '15:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 1), '15:10:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '15:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 2), '15:18:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '15:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 3), '15:27:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '15:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 4), '15:39:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '15:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 5), '15:45:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '16:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 0), '16:00:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '16:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 1), '16:11:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '16:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 2), '16:19:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '16:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 3), '16:29:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '16:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 4), '16:37:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '16:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 5), '16:46:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '17:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 0), '17:00:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '17:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 1), '17:09:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '17:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 2), '17:21:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '17:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 3), '17:32:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '17:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 4), '17:41:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '17:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 5), '17:49:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '18:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 0), '18:00:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '18:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 1), '18:06:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '18:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 2), '18:12:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '18:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 3), '18:22:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '18:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 4), '18:34:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '18:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 5), '18:45:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '19:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 0), '19:00:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '19:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 1), '19:07:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '19:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 2), '19:16:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '19:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 3), '19:23:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '19:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 4), '19:33:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '19:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 5), '19:45:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '20:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 0), '20:00:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '20:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 1), '20:12:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '20:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 2), '20:26:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '20:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 3), '20:39:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '20:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 4), '20:46:00'),
((select id from track where line_id = (select id from line where line_name = '1') and start_time = '20:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '1') and r.order = 5), '21:00:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '12:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 0), '12:30:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '12:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 1), '12:40:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '12:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 2), '12:48:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '12:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 3), '12:59:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '12:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 4), '13:05:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '12:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 5), '13:13:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '15:20:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 0), '15:20:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '15:20:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 1), '15:29:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '15:20:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 2), '15:37:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '15:20:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 3), '15:47:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '15:20:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 4), '15:53:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '15:20:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 5), '16:05:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '18:10:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 0), '18:10:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '18:10:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 1), '18:16:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '18:10:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 2), '18:22:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '18:10:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 3), '18:32:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '18:10:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 4), '18:46:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '18:10:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 5), '18:55:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '22:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 0), '22:00:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '22:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 1), '22:06:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '22:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 2), '22:16:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '22:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 3), '22:25:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '22:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 4), '22:38:00'),
((select id from track where line_id = (select id from line where line_name = '2') and start_time = '22:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '2') and r.order = 5), '22:44:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '19:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 0), '19:00:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '19:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 1), '19:14:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '19:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 2), '19:28:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '19:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 3), '19:36:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '19:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 4), '19:42:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '19:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 5), '19:50:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '19:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 6), '19:56:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '20:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 0), '20:00:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '20:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 1), '20:11:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '20:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 2), '20:24:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '20:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 3), '20:33:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '20:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 4), '20:39:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '20:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 5), '20:50:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '20:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 6), '20:57:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '21:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 0), '21:00:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '21:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 1), '21:07:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '21:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 2), '21:18:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '21:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 3), '21:30:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '21:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 4), '21:41:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '21:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 5), '21:54:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '21:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 6), '22:05:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '22:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 0), '22:00:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '22:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 1), '22:13:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '22:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 2), '22:20:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '22:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 3), '22:32:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '22:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 4), '22:41:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '22:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 5), '22:54:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '22:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 6), '23:07:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '23:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 0), '23:00:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '23:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 1), '23:07:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '23:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 2), '23:17:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '23:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 3), '23:26:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '23:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 4), '23:40:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '23:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 5), '23:49:00'),
((select id from track where line_id = (select id from line where line_name = '3') and start_time = '23:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = '3') and r.order = 6), '00:00:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '09:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 0), '09:30:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '09:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 1), '09:42:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '09:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 2), '09:53:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '09:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 3), '10:01:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '09:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 4), '10:07:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '09:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 5), '10:14:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '09:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 0), '09:00:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '09:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 1), '09:10:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '09:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 2), '09:21:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '09:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 3), '09:34:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '09:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 4), '09:47:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '09:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 5), '10:01:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '12:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 0), '12:00:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '12:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 1), '12:10:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '12:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 2), '12:20:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '12:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 3), '12:33:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '12:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 4), '12:40:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '12:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 5), '12:50:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '12:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 0), '12:30:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '12:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 1), '12:44:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '12:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 2), '12:52:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '12:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 3), '12:59:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '12:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 4), '13:05:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '12:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 5), '13:18:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '15:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 0), '15:30:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '15:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 1), '15:44:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '15:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 2), '15:56:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '15:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 3), '16:04:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '15:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 4), '16:11:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '15:30:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 5), '16:22:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '15:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 0), '15:00:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '15:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 1), '15:08:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '15:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 2), '15:14:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '15:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 3), '15:23:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '15:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 4), '15:32:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '15:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 5), '15:40:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '20:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 0), '20:00:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '20:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 1), '20:08:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '20:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 2), '20:20:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '20:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 3), '20:28:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '20:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 4), '20:40:00'),
((select id from track where line_id = (select id from line where line_name = 'A') and start_time = '20:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'A') and r.order = 5), '20:53:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '07:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 0), '07:00:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '07:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 1), '07:10:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '07:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 2), '07:19:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '07:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 3), '07:32:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '07:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 4), '07:42:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '07:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 5), '07:53:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '08:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 0), '08:00:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '08:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 1), '08:12:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '08:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 2), '08:22:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '08:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 3), '08:28:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '08:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 4), '08:41:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '08:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 5), '08:47:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '09:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 0), '09:00:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '09:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 1), '09:14:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '09:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 2), '09:27:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '09:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 3), '09:36:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '09:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 4), '09:44:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '09:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 5), '09:56:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '10:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 0), '10:00:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '10:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 1), '10:12:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '10:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 2), '10:26:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '10:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 3), '10:36:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '10:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 4), '10:43:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '10:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 5), '10:57:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '11:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 0), '11:00:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '11:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 1), '11:12:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '11:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 2), '11:19:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '11:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 3), '11:27:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '11:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 4), '11:33:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '11:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 5), '11:43:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '12:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 0), '12:00:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '12:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 1), '12:07:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '12:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 2), '12:13:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '12:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 3), '12:22:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '12:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 4), '12:32:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '12:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 5), '12:44:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '13:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 0), '13:00:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '13:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 1), '13:12:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '13:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 2), '13:22:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '13:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 3), '13:28:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '13:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 4), '13:41:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '13:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 5), '13:54:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '14:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 0), '14:00:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '14:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 1), '14:06:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '14:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 2), '14:13:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '14:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 3), '14:27:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '14:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 4), '14:40:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '14:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 5), '14:48:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '15:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 0), '15:00:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '15:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 1), '15:11:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '15:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 2), '15:18:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '15:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 3), '15:29:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '15:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 4), '15:40:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '15:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 5), '15:54:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '16:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 0), '16:00:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '16:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 1), '16:06:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '16:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 2), '16:14:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '16:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 3), '16:23:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '16:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 4), '16:34:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '16:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 5), '16:48:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '17:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 0), '17:00:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '17:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 1), '17:06:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '17:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 2), '17:17:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '17:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 3), '17:28:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '17:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 4), '17:37:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '17:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 5), '17:46:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '18:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 0), '18:00:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '18:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 1), '18:12:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '18:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 2), '18:22:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '18:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 3), '18:31:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '18:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 4), '18:37:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '18:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 5), '18:44:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '19:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 0), '19:00:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '19:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 1), '19:14:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '19:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 2), '19:22:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '19:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 3), '19:32:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '19:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 4), '19:38:00'),
((select id from track where line_id = (select id from line where line_name = 'B') and start_time = '19:00:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'B') and r.order = 5), '19:49:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '06:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 0), '06:15:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '06:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 1), '06:22:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '06:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 2), '06:33:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '06:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 3), '06:42:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '06:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 4), '06:56:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '06:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 5), '07:06:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '06:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 6), '07:19:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '06:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 0), '06:45:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '06:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 1), '06:57:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '06:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 2), '07:03:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '06:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 3), '07:09:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '06:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 4), '07:20:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '06:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 5), '07:27:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '06:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 6), '07:41:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '07:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 0), '07:15:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '07:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 1), '07:22:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '07:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 2), '07:29:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '07:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 3), '07:38:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '07:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 4), '07:52:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '07:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 5), '08:06:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '07:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 6), '08:19:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '07:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 0), '07:45:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '07:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 1), '07:59:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '07:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 2), '08:10:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '07:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 3), '08:23:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '07:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 4), '08:31:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '07:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 5), '08:39:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '07:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 6), '08:49:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '08:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 0), '08:15:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '08:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 1), '08:25:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '08:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 2), '08:36:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '08:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 3), '08:48:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '08:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 4), '08:58:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '08:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 5), '09:04:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '08:15:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 6), '09:11:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '08:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 0), '08:45:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '08:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 1), '08:53:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '08:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 2), '09:00:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '08:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 3), '09:06:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '08:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 4), '09:15:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '08:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 5), '09:21:00'),
((select id from track where line_id = (select id from line where line_name = 'C') and start_time = '08:45:00'), (select id from route r where line_id = (select id from line l where l.line_name = 'C') and r.order = 6), '09:32:00')
;

--ride injection
insert into ride (bus_id, driver_id, track_id, date) values
(3,(select id from driver where name = 'Kamil' and lastname = 'Nabozny'),(select id from track where line_id = (select id from line where line_name = '1') and start_time = '10:00:00'),'2024-05-16'),
(5,(select id from driver where name = 'Jan' and lastname = 'Kowalski'),(select id from track where line_id = (select id from line where line_name = '1') and start_time = '11:00:00'),'2024-05-16'),
(2,(select id from driver where name = 'Alan' and lastname = 'Pawleta'),(select id from track where line_id = (select id from line where line_name = '1') and start_time = '12:00:00'),'2024-05-16'),
(4,(select id from driver where name = 'Bartosz' and lastname = 'Pokorski'),(select id from track where line_id = (select id from line where line_name = '1') and start_time = '13:00:00'),'2024-05-16'),
(2,(select id from driver where name = 'Alan' and lastname = 'Pawleta'),(select id from track where line_id = (select id from line where line_name = '1') and start_time = '14:00:00'),'2024-05-16'),
(3,(select id from driver where name = 'Kamil' and lastname = 'Nabozny'),(select id from track where line_id = (select id from line where line_name = '1') and start_time = '15:00:00'),'2024-05-16'),
(3,(select id from driver where name = 'Kamil' and lastname = 'Nabozny'),(select id from track where line_id = (select id from line where line_name = '1') and start_time = '16:00:00'),'2024-05-16'),
(5,(select id from driver where name = 'Jan' and lastname = 'Kowalski'),(select id from track where line_id = (select id from line where line_name = '1') and start_time = '17:00:00'),'2024-05-16'),
(6,(select id from driver where name = 'Lukasz' and lastname = 'Wojczuk'),(select id from track where line_id = (select id from line where line_name = '1') and start_time = '18:00:00'),'2024-05-16'),
(3,(select id from driver where name = 'Kamil' and lastname = 'Nabozny'),(select id from track where line_id = (select id from line where line_name = '1') and start_time = '19:00:00'),'2024-05-16'),
(5,(select id from driver where name = 'Jan' and lastname = 'Kowalski'),(select id from track where line_id = (select id from line where line_name = '1') and start_time = '20:00:00'),'2024-05-16'),
(6,(select id from driver where name = 'Lukasz' and lastname = 'Wojczuk'),(select id from track where line_id = (select id from line where line_name = '2') and start_time = '12:30:00'),'2024-05-16'),
(4,(select id from driver where name = 'Bartosz' and lastname = 'Pokorski'),(select id from track where line_id = (select id from line where line_name = '2') and start_time = '15:20:00'),'2024-05-16'),
(1,(select id from driver where name = 'Nikodem' and lastname = 'Wspanialy'),(select id from track where line_id = (select id from line where line_name = '2') and start_time = '18:10:00'),'2024-05-16'),
(2,(select id from driver where name = 'Alan' and lastname = 'Pawleta'),(select id from track where line_id = (select id from line where line_name = '2') and start_time = '22:00:00'),'2024-05-16'),
(4,(select id from driver where name = 'Bartosz' and lastname = 'Pokorski'),(select id from track where line_id = (select id from line where line_name = '3') and start_time = '19:00:00'),'2024-05-16'),
(4,(select id from driver where name = 'Bartosz' and lastname = 'Pokorski'),(select id from track where line_id = (select id from line where line_name = '3') and start_time = '20:00:00'),'2024-05-16'),
(4,(select id from driver where name = 'Bartosz' and lastname = 'Pokorski'),(select id from track where line_id = (select id from line where line_name = '3') and start_time = '21:00:00'),'2024-05-16'),
(4,(select id from driver where name = 'Bartosz' and lastname = 'Pokorski'),(select id from track where line_id = (select id from line where line_name = '3') and start_time = '22:00:00'),'2024-05-16'),
(2,(select id from driver where name = 'Alan' and lastname = 'Pawleta'),(select id from track where line_id = (select id from line where line_name = '3') and start_time = '23:00:00'),'2024-05-16'),
(5,(select id from driver where name = 'Jan' and lastname = 'Kowalski'),(select id from track where line_id = (select id from line where line_name = 'A') and start_time = '09:30:00'),'2024-05-16'),
(6,(select id from driver where name = 'Lukasz' and lastname = 'Wojczuk'),(select id from track where line_id = (select id from line where line_name = 'A') and start_time = '09:00:00'),'2024-05-16'),
(3,(select id from driver where name = 'Kamil' and lastname = 'Nabozny'),(select id from track where line_id = (select id from line where line_name = 'A') and start_time = '12:00:00'),'2024-05-16'),
(6,(select id from driver where name = 'Lukasz' and lastname = 'Wojczuk'),(select id from track where line_id = (select id from line where line_name = 'A') and start_time = '12:30:00'),'2024-05-16'),
(1,(select id from driver where name = 'Nikodem' and lastname = 'Wspanialy'),(select id from track where line_id = (select id from line where line_name = 'A') and start_time = '15:30:00'),'2024-05-16'),
(4,(select id from driver where name = 'Bartosz' and lastname = 'Pokorski'),(select id from track where line_id = (select id from line where line_name = 'A') and start_time = '15:00:00'),'2024-05-16'),
(6,(select id from driver where name = 'Lukasz' and lastname = 'Wojczuk'),(select id from track where line_id = (select id from line where line_name = 'A') and start_time = '20:00:00'),'2024-05-16'),
(5,(select id from driver where name = 'Jan' and lastname = 'Kowalski'),(select id from track where line_id = (select id from line where line_name = 'B') and start_time = '07:00:00'),'2024-05-16'),
(6,(select id from driver where name = 'Lukasz' and lastname = 'Wojczuk'),(select id from track where line_id = (select id from line where line_name = 'B') and start_time = '08:00:00'),'2024-05-16'),
(4,(select id from driver where name = 'Bartosz' and lastname = 'Pokorski'),(select id from track where line_id = (select id from line where line_name = 'B') and start_time = '09:00:00'),'2024-05-16'),
(3,(select id from driver where name = 'Kamil' and lastname = 'Nabozny'),(select id from track where line_id = (select id from line where line_name = 'B') and start_time = '10:00:00'),'2024-05-16'),
(1,(select id from driver where name = 'Nikodem' and lastname = 'Wspanialy'),(select id from track where line_id = (select id from line where line_name = 'B') and start_time = '11:00:00'),'2024-05-16'),
(2,(select id from driver where name = 'Alan' and lastname = 'Pawleta'),(select id from track where line_id = (select id from line where line_name = 'B') and start_time = '12:00:00'),'2024-05-16'),
(4,(select id from driver where name = 'Bartosz' and lastname = 'Pokorski'),(select id from track where line_id = (select id from line where line_name = 'B') and start_time = '13:00:00'),'2024-05-16'),
(4,(select id from driver where name = 'Bartosz' and lastname = 'Pokorski'),(select id from track where line_id = (select id from line where line_name = 'B') and start_time = '14:00:00'),'2024-05-16'),
(6,(select id from driver where name = 'Lukasz' and lastname = 'Wojczuk'),(select id from track where line_id = (select id from line where line_name = 'B') and start_time = '15:00:00'),'2024-05-16'),
(1,(select id from driver where name = 'Nikodem' and lastname = 'Wspanialy'),(select id from track where line_id = (select id from line where line_name = 'B') and start_time = '16:00:00'),'2024-05-16'),
(2,(select id from driver where name = 'Alan' and lastname = 'Pawleta'),(select id from track where line_id = (select id from line where line_name = 'B') and start_time = '17:00:00'),'2024-05-16'),
(3,(select id from driver where name = 'Kamil' and lastname = 'Nabozny'),(select id from track where line_id = (select id from line where line_name = 'B') and start_time = '18:00:00'),'2024-05-16'),
(6,(select id from driver where name = 'Lukasz' and lastname = 'Wojczuk'),(select id from track where line_id = (select id from line where line_name = 'B') and start_time = '19:00:00'),'2024-05-16'),
(6,(select id from driver where name = 'Lukasz' and lastname = 'Wojczuk'),(select id from track where line_id = (select id from line where line_name = 'C') and start_time = '06:15:00'),'2024-05-16'),
(2,(select id from driver where name = 'Alan' and lastname = 'Pawleta'),(select id from track where line_id = (select id from line where line_name = 'C') and start_time = '06:45:00'),'2024-05-16'),
(6,(select id from driver where name = 'Lukasz' and lastname = 'Wojczuk'),(select id from track where line_id = (select id from line where line_name = 'C') and start_time = '07:15:00'),'2024-05-16'),
(3,(select id from driver where name = 'Kamil' and lastname = 'Nabozny'),(select id from track where line_id = (select id from line where line_name = 'C') and start_time = '07:45:00'),'2024-05-16'),
(4,(select id from driver where name = 'Bartosz' and lastname = 'Pokorski'),(select id from track where line_id = (select id from line where line_name = 'C') and start_time = '08:15:00'),'2024-05-16'),
(2,(select id from driver where name = 'Alan' and lastname = 'Pawleta'),(select id from track where line_id = (select id from line where line_name = 'C') and start_time = '08:45:00'),'2024-05-16')

END;